version: '3'
services:
  db:
    image: pygmy-db
    build: ./db/
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pygmy
      - MYSQL_USER=pygmy
      - MYSQL_PASSWORD=pygmy
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    networks:
      - db
  backend:
    image: pygmy-backend
    build: ./backend/
    environment:
      - NODE_ENV=production
      - DB_USERNAME=pygmy
      - DB_PASSWORD=pygmy
      - DB_DATABASE=pygmy
      - DB_HOST=db
      - DB_DIALECT=mysql
      - DB_TIMEZONE=+09:00
    ports:
      - 3000:3000
    networks:
      - db
    depends_on:
      - db
networks:
  # gitlab:
  #   driver: bridge
  #   ipam: 
  #     driver: default
  #     config:
  #       - subnet: 192.168.100.0/24
  db:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 192.168.10.0/24
